const RealmeModels = [
  {
    id: 1,
    code: "001",
    model: "Realme 5",
    type: "Tempered Glass",
    location: "Aisle 3, Shelf 2",
    quantity: 10,
    purchasePrice: 5.0,
    salePrice: 10.0,
    compatibleModels: [
      "Realme 5",
      "Realme 5S",
      "Realme 8",
      "Realme 10",
      "Realme 50",
      "Realme 108",
      "Realme 10T 5G",
      "Realme C3",
      "Realme C11",
      "Realme C12",
      "Realme C15",
      "Realme C20",
      "Realme C20A",
      "Realme C21",
      "Realme C2TY",
      "Realme C25",
      "Realme C258",
      "Realme C25Y",
      "Realme C30",
      "Realme C385",
      "Realme C31",
      "Realme C33",
      "Realme C35",
      "Realme C3",
      "Realme NARZO 10",
      "Realme NARZO 20",
      "Realme NARZO 20A",
      "Realme NARZO 30A",
      "Realme NARZO 50 5G",
      "Realme NARZO 50A",
      "Realme NARZO 50",
      "Realme V11",
      "Realme V20",
      "Realme V23",
      "Realme OPA11",
      "Realme A11X",
      "Realme A15",
      "Realme A155",
      "Realme A16",
      "Realme A16E",
      "Realme A18",
      "Realme KJA188",
      "Realme A17",
      "Realme A17K",
      "Realme A31",
      "Realme A35",
      "Realme A38",
      "Realme A5 2020",
      "Realme A535 5G",
      "Realme A55 SG",
      "Realme A56 5G",
      "Realme AST 4G",
      "Realme AST 5G",
      "Realme ASTEJA58",
      "Realme A77 4G",
      "Realme A77 A7756",
      "Realme A77S",
      "Realme A78",
      "Realme A8",
      "Realme A9 2020",
      "Realme A87",
      "Realme INF HOTS",
      "Realme HOT 10W",
      "Realme HOT 11",
      "Realme HOT 12 PRO",
      "Realme HOT 20",
      "Realme HOT 301",
      "Realme SMART7",
      "Realme SMART7 (INDIA)",
      "Realme SMART7+",
      "Realme SMARTY HO",
      "Realme SMARTS HD",
      "Realme ITEL $18",
      "Realme A60",
      "Realme 1+NORD N300",
      "Realme TEC SPARK 10",
      "Realme UTELS SPARK 10C",
      "Realme SPARK GO 2 2023",
      "Realme SPARKS PRO",
      "Realme NOTE11",
      "Realme NOTE12",
      "Realme NOTE 12 PRO",
      "Realme NOTE 11E",
      "Realme SMARTSH",
      "Realme HOT 12",
      "Realme SPARK44 LITES OG",
      "Realme FITTIN #T",
      "Realme VO YOU",
      "Realme Y",
      "Realme YZA",
      "Realme Y02S",
      "Realme Y2T",
      "Realme Y115",
      "Realme Y11",
      "Realme Y46 2023",
      "Realme Y12A",
      "Realme Y120",
      "Realme Y125",
      "Realme Y15A",
      "Realme Y155",
      "Realme Y28",
      "Realme Y285",
      "Realme Y205 G",
      "Realme Y21",
      "Realme Y21A",
      "Realme Y21E",
      "Realme Y218",
      "Realme Y217",
      "Realme 22",
      "Realme 225",
      "Realme 27 2023",
      "Realme 931",
      "Realme 32",
      "Realme 33",
      "Realme 35",
      "Realme 35+",
      "Realme Y36 (INDIA)",
      "Realme YS1 2020",
      "Realme YS1A",
      "Realme V52 5G",
      "Realme Y525",
      "Realme YSZT",
      "Realme Y535",
      "Realme Y545",
      "Realme Y55 5G",
      "Realme Y56",
      "Realme 772 50",
      "Realme Y7ZT",
      "Realme Y748",
      "Realme Y75 50",
      "Realme Y76 5G",
      "Realme Y765",
      "Realme 77",
      "Realme 150",
      "Realme T1 SG",
      "Realme T1X",
      "Realme T1X 40",
      "Realme T2X 5G",
      "Realme IQOO 23",
      "Realme 1000",
      "Realme 26",
      "Realme BAM AG2JA025",
      "Realme A03",
      "Realme 403SAS CORE",
      "Realme A0404",
      "Realme A0404 CORE",
      "Realme IMAIFDA A12",
      "Realme A13",
      "Realme A13 5G",
      "Realme ASIA23 50",
      "Realme A32-50",
      "Realme 025",
      "Realme F12",
      "Realme F13",
      "Realme F23",
      "Realme 02",
      "Realme 025",
      "Realme M12",
      "Realme M13",
      "Realme M135G",
      "Realme M2",
      "Realme M32 50",
      "Realme M/13",
      "Realme RM1A1-A2+",
      "Realme 10 050",
      "Realme 11 PRIME",
      "Realme 11 PRIME 50",
      "Realme POCO C3",
      "Realme POCO CS1",
      "Realme POCO MA",
      "Realme POCO MS",
      "Realme MI",
      "Realme POCO CS",
      "Realme POCO CS1",
    ],
  },
];

export default RealmeModels;
