const data = {
  items: [
    {
      code: "001",
      name: "Phone Charger",
      quantity: 100,
      purchasePrice: 500,
      salePrice: 600,
    },
    {
      code: "002",
      name: "Phone Case",
      quantity: 200,
      purchasePrice: 300,
      salePrice: 400,
    },
    {
      code: "003",
      name: "Screen Protector",
      quantity: 150,
      purchasePrice: 200,
      salePrice: 250,
    },
    {
      code: "004",
      name: "Wireless Earbuds",
      quantity: 80,
      purchasePrice: 1500,
      salePrice: 1800,
    },
    {
      code: "005",
      name: "USB Cable",
      quantity: 90,
      purchasePrice: 150,
      salePrice: 200,
    },
    {
      code: "006",
      name: "Power Bank",
      quantity: 60,
      purchasePrice: 1000,
      salePrice: 1200,
    },
    {
      code: "007",
      name: "Car Mount",
      quantity: 120,
      purchasePrice: 400,
      salePrice: 500,
    },
    {
      code: "008",
      name: "Bluetooth Speaker",
      quantity: 70,
      purchasePrice: 1200,
      salePrice: 1400,
    },
    {
      code: "009",
      name: "Headphones",
      quantity: 50,
      purchasePrice: 800,
      salePrice: 1000,
    },
    {
      code: "010",
      name: "Phone Stand",
      quantity: 110,
      purchasePrice: 200,
      salePrice: 300,
    },
    {
      code: "011",
      name: "Portable Fan",
      quantity: 90,
      purchasePrice: 600,
      salePrice: 750,
    },
    {
      code: "012",
      name: "Charging Dock",
      quantity: 65,
      purchasePrice: 800,
      salePrice: 950,
    },
    {
      code: "013",
      name: "Car Charger",
      quantity: 85,
      purchasePrice: 400,
      salePrice: 500,
    },
    {
      code: "014",
      name: "Smartwatch Band",
      quantity: 100,
      purchasePrice: 300,
      salePrice: 400,
    },
    {
      code: "015",
      name: "Stylus Pen",
      quantity: 130,
      purchasePrice: 150,
      salePrice: 200,
    },
    {
      code: "016",
      name: "Cable Organizer",
      quantity: 75,
      purchasePrice: 100,
      salePrice: 150,
    },
    {
      code: "017",
      name: "Phone Cleaning Kit",
      quantity: 60,
      purchasePrice: 250,
      salePrice: 300,
    },
    {
      code: "018",
      name: "Camera Lens Protector",
      quantity: 40,
      purchasePrice: 180,
      salePrice: 220,
    },
    {
      code: "019",
      name: "Mobile Holder for Bike",
      quantity: 55,
      purchasePrice: 500,
      salePrice: 600,
    },
    {
      code: "020",
      name: "Gaming Controller",
      quantity: 30,
      purchasePrice: 2500,
      salePrice: 3000,
    },
    {
      code: "021",
      name: "LED Phone Case",
      quantity: 50,
      purchasePrice: 1000,
      salePrice: 1200,
    },
    {
      code: "022",
      name: "USB OTG Adapter",
      quantity: 70,
      purchasePrice: 150,
      salePrice: 200,
    },
    {
      code: "023",
      name: "Screen Cleaning Cloth",
      quantity: 95,
      purchasePrice: 50,
      salePrice: 80,
    },
    {
      code: "024",
      name: "Phone Wallet Case",
      quantity: 85,
      purchasePrice: 700,
      salePrice: 900,
    },
    {
      code: "025",
      name: "Charging Cable Organizer",
      quantity: 40,
      purchasePrice: 200,
      salePrice: 250,
    },
    {
      code: "026",
      name: "Mini Tripod",
      quantity: 100,
      purchasePrice: 400,
      salePrice: 500,
    },
    {
      code: "027",
      name: "Phone Grip Stand",
      quantity: 55,
      purchasePrice: 150,
      salePrice: 200,
    },
    {
      code: "028",
      name: "Magnetic Charging Cable",
      quantity: 60,
      purchasePrice: 350,
      salePrice: 450,
    },
    {
      code: "029",
      name: "Wireless Charging Pad",
      quantity: 45,
      purchasePrice: 800,
      salePrice: 1000,
    },
    {
      code: "030",
      name: "Foldable Phone Stand",
      quantity: 70,
      purchasePrice: 250,
      salePrice: 300,
    },
    {
      code: "031",
      name: "Noise Cancelling Earphones",
      quantity: 40,
      purchasePrice: 1200,
      salePrice: 1500,
    },
    {
      code: "032",
      name: "Smartphone Gimbal",
      quantity: 30,
      purchasePrice: 3000,
      salePrice: 3500,
    },
    {
      code: "033",
      name: "Selfie Stick",
      quantity: 85,
      purchasePrice: 400,
      salePrice: 500,
    },
    {
      code: "034",
      name: "Phone Cleaning Spray",
      quantity: 55,
      purchasePrice: 150,
      salePrice: 200,
    },
    {
      code: "035",
      name: "Anti-Drop Phone Case",
      quantity: 90,
      purchasePrice: 500,
      salePrice: 600,
    },
    {
      code: "036",
      name: "Fitness Tracker",
      quantity: 70,
      purchasePrice: 2000,
      salePrice: 2500,
    },
    {
      code: "037",
      name: "Universal Phone Charger",
      quantity: 65,
      purchasePrice: 300,
      salePrice: 400,
    },
    {
      code: "038",
      name: "Phone Battery Case",
      quantity: 80,
      purchasePrice: 1000,
      salePrice: 1200,
    },
    {
      code: "039",
      name: "External Battery Pack",
      quantity: 55,
      purchasePrice: 1200,
      salePrice: 1500,
    },
    {
      code: "040",
      name: "Phone Lens Kit",
      quantity: 60,
      purchasePrice: 800,
      salePrice: 1000,
    },
    {
      code: "041",
      name: "Mobile Phone Holder",
      quantity: 50,
      purchasePrice: 400,
      salePrice: 500,
    },
    {
      code: "042",
      name: "Wireless Headphones",
      quantity: 75,
      purchasePrice: 1500,
      salePrice: 1800,
    },
    {
      code: "043",
      name: "Fast Charging Adapter",
      quantity: 65,
      purchasePrice: 500,
      salePrice: 600,
    },
    {
      code: "044",
      name: "Bluetooth Keyboard",
      quantity: 55,
      purchasePrice: 1200,
      salePrice: 1500,
    },
    {
      code: "045",
      name: "Phone Screen Magnifier",
      quantity: 40,
      purchasePrice: 350,
      salePrice: 450,
    },
    {
      code: "046",
      name: "Portable Speaker",
      quantity: 30,
      purchasePrice: 1000,
      salePrice: 1300,
    },
    {
      code: "047",
      name: "Smartphone Holder for Car",
      quantity: 90,
      purchasePrice: 200,
      salePrice: 250,
    },
    {
      code: "048",
      name: "Magnetic Phone Mount",
      quantity: 65,
      purchasePrice: 250,
      salePrice: 300,
    },
    {
      code: "049",
      name: "Phone Armband",
      quantity: 50,
      purchasePrice: 150,
      salePrice: 200,
    },
    {
      code: "050",
      name: "Memory Card Reader",
      quantity: 70,
      purchasePrice: 300,
      salePrice: 350,
    },
  ],
};

export default data;
