const data = {
  items: [
    {
      code: "0001",
      name: "SAMSUNG ADOPTER 25W charger",
      quantity: 6,
      purchasePrice: 550,
      salePrice: 1250,
    },
    {
      code: "0002",
      name: "Iphone adopter 25W charger 3pin",
      quantity: 1,
      purchasePrice: 750,
      salePrice: 2000,
    },
    {
      code: "0003",
      name: "Ronin R29 handfree smartphone",
      quantity: 6,
      purchasePrice: 350,
      salePrice: 795,
    },
    {
      code: "0004",
      name: "Ronin R9 handfree smartphone",
      quantity: 6,
      purchasePrice: 460,
      salePrice: 995,
    },
    {
      code: "0005",
      name: "Faster F15 handfree",
      quantity: 3,
      purchasePrice: 238,
      salePrice: 450,
    },
    {
      code: "0006",
      name: "Faster F9 handree",
      quantity: 3,
      purchasePrice: 268,
      salePrice: 550,
    },
    {
      code: "0007",
      name: "mobile back skin 3d sheet",
      quantity: 111,
      purchasePrice: 125,
      salePrice: 500,
    },
    {
      code: "0008",
      name: "Faster TG-330 Neckband",
      quantity: 2,
      purchasePrice: 2350,
      salePrice: 3500,
    },
    {
      code: "0009",
      name: "Ronin R-970 Neckband wireless headphones",
      quantity: 2,
      purchasePrice: 1900,
      salePrice: 3000,
    },
    {
      code: "0010",
      name: "privacy mate sheet front screen",
      quantity: 5,
      purchasePrice: 290,
      salePrice: 650,
    },
    {
      code: "0011",
      name: "Clear Privacy sheet front screen",
      quantity: 5,
      purchasePrice: 290,
      salePrice: 650,
    },
    {
      code: "0012",
      name: "mate front screen sheet hydrogel",
      quantity: 10,
      purchasePrice: 120,
      salePrice: 300,
    },
    {
      code: "0013",
      name: "HD front screen sheet hydrogel",
      quantity: 10,
      purchasePrice: 120,
      salePrice: 300,
    },
    {
      code: "0014",
      name: "OPPO adopter 67W charger",
      quantity: 6,
      purchasePrice: 340,
      salePrice: 850,
    },
    {
      code: "0015",
      name: "Vivo adopter 67W charger",
      quantity: 6,
      purchasePrice: 340,
      salePrice: 850,
    },
    {
      code: "0016",
      name: "One Plus data cable",
      quantity: 10,
      purchasePrice: 100,
      salePrice: 300,
    },
    {
      code: "0017",
      name: "Gionee handree",
      quantity: 10,
      purchasePrice: 120,
      salePrice: 300,
    },
    {
      code: "0018",
      name: "mix media boofer voofer handree",
      quantity: 20,
      purchasePrice: 130,
      salePrice: 450,
    },
    {
      code: "0019",
      name: "BMT handfree",
      quantity: 12,
      purchasePrice: 130,
      salePrice: 450,
    },
    {
      code: "0020",
      name: "OTG pin Type-C ",
      quantity: 10,
      purchasePrice: 15,
      salePrice: 100,
    },
    {
      code: "0021",
      name: "anywarshy handree",
      quantity: 1,
      purchasePrice: 220,
      salePrice: 500,
    },
    {
      code: "0022",
      name: "Card Reader",
      quantity: 30,
      purchasePrice: 10,
      salePrice: 100,
    },
    {
      code: "0023",
      name: "Finzu Cable fast charging 6A",
      quantity: 10,
      purchasePrice: 75,
      salePrice: 250,
    },
    {
      code: "0024",
      name: "Iphone 60 type-C Cable",
      quantity: 5,
      purchasePrice: 130,
      salePrice: 350,
    },
    {
      code: "0025",
      name: "Poxsoon",
      quantity: 5,
      purchasePrice: 65,
      salePrice: 200,
    },
    {
      code: "0026",
      name: "Vatnam Handfree boofer",
      quantity: 10,
      purchasePrice: 85,
      salePrice: 300,
    },
    {
      code: "0027",
      name: "Sim ejector pin",
      quantity: 100,
      purchasePrice: 1,
      salePrice: 20,
    },
    {
      code: "0028",
      name: "Mi6 Adopter fast charger",
      quantity: 3,
      purchasePrice: 250,
      salePrice: 600,
    },
    {
      code: "0029",
      name: "Super ASUS Adopter fast charger",
      quantity: 6,
      purchasePrice: 260,
      salePrice: 750,
    },
    {
      code: "0030",
      name: "Iphone 20W adopter fast cahrging 2pin",
      quantity: 1,
      purchasePrice: 550,
      salePrice: 2000,
    },
    {
      code: "0031",
      name: "A9 ANC touch screen earbuds white",
      quantity: 1,
      purchasePrice: 1750,
      salePrice: 4250,
    },
    {
      code: "0032",
      name: "A9 ANC touch screen earbuds black",
      quantity: 1,
      purchasePrice: 1850,
      salePrice: 4500,
    },
    {
      code: "0033",
      name: "Infinix Hot 30i smartphone 8/128",
      quantity: 1,
      purchasePrice: 25500,
      salePrice: 28000,
    },
  ],
};

export default data;
